"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ibgeNomesMunicipiosDesc = exports.ibgeNomesMunicipiosAsc = exports.ibgeNomesMunicipios = exports.ibgeNomesEstadosDesc = exports.ibgeNomesEstadosAsc = exports.ibgeNomesEstados = exports.ibgeSiglasEstadosDesc = exports.ibgeSiglasEstadosAsc = exports.ibgeSiglasEstados = exports.ibgeMunicipios = exports.ibgeEstados = void 0;
const localidades_1 = require("./localidades");
Object.defineProperty(exports, "ibgeEstados", { enumerable: true, get: function () { return localidades_1.ibgeEstados; } });
Object.defineProperty(exports, "ibgeMunicipios", { enumerable: true, get: function () { return localidades_1.ibgeMunicipios; } });
Object.defineProperty(exports, "ibgeSiglasEstados", { enumerable: true, get: function () { return localidades_1.ibgeSiglasEstados; } });
Object.defineProperty(exports, "ibgeSiglasEstadosAsc", { enumerable: true, get: function () { return localidades_1.ibgeSiglasEstadosAsc; } });
Object.defineProperty(exports, "ibgeSiglasEstadosDesc", { enumerable: true, get: function () { return localidades_1.ibgeSiglasEstadosDesc; } });
Object.defineProperty(exports, "ibgeNomesEstados", { enumerable: true, get: function () { return localidades_1.ibgeNomesEstados; } });
Object.defineProperty(exports, "ibgeNomesEstadosAsc", { enumerable: true, get: function () { return localidades_1.ibgeNomesEstadosAsc; } });
Object.defineProperty(exports, "ibgeNomesEstadosDesc", { enumerable: true, get: function () { return localidades_1.ibgeNomesEstadosDesc; } });
Object.defineProperty(exports, "ibgeNomesMunicipios", { enumerable: true, get: function () { return localidades_1.ibgeNomesMunicipios; } });
Object.defineProperty(exports, "ibgeNomesMunicipiosAsc", { enumerable: true, get: function () { return localidades_1.ibgeNomesMunicipiosAsc; } });
Object.defineProperty(exports, "ibgeNomesMunicipiosDesc", { enumerable: true, get: function () { return localidades_1.ibgeNomesMunicipiosDesc; } });
